import type { Config } from 'tailwindcss';

/**
 * "Cyber Level Narrative" design system.
 * Tokens ported 1:1 from design_idea/DESIGN.md so the production build
 * matches the approved mock. Animations are added for the game/terminal feel.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00201e',
        'secondary-container': '#007f7f',
        'on-error': '#690005',
        'tertiary-container': '#e9865b',
        'on-surface-variant': '#bbc9c7',
        'on-error-container': '#ffdad6',
        'primary-container': '#20b2aa',
        'primary-fixed-dim': '#59dad1',
        'on-primary': '#003734',
        'outline-variant': '#3c4948',
        'surface-container-low': '#1b1b1c',
        'terminal-bg': '#0A0A0A',
        'surface-bright': '#393939',
        'on-primary-fixed-variant': '#00504c',
        'surface-container-high': '#2a2a2a',
        'on-secondary-fixed-variant': '#004f4f',
        'surface-container-lowest': '#0e0e0e',
        error: '#ffb4ab',
        tertiary: '#ffb597',
        'surface-container': '#202020',
        'glass-fill': 'rgba(31, 31, 31, 0.6)',
        'secondary-fixed': '#93f2f2',
        'on-surface': '#e5e2e1',
        'primary-fixed': '#79f6ed',
        'tertiary-fixed-dim': '#ffb597',
        'on-background': '#e5e2e1',
        'on-secondary-fixed': '#002020',
        'error-red': '#FF4B4B',
        'error-container': '#93000a',
        primary: '#59dad1',
        'secondary-fixed-dim': '#76d6d5',
        'on-primary-container': '#003e3b',
        'on-secondary': '#003737',
        'inverse-on-surface': '#303030',
        'on-tertiary': '#591d00',
        'on-tertiary-fixed-variant': '#79300b',
        secondary: '#76d6d5',
        'inverse-primary': '#006a65',
        'surface-variant': '#353535',
        background: '#131313',
        'surface-container-highest': '#353535',
        surface: '#131313',
        'on-tertiary-container': '#632200',
        'on-tertiary-fixed': '#360f00',
        'inverse-surface': '#e5e2e1',
        'surface-dim': '#131313',
        'surface-tint': '#59dad1',
        'glow-teal': 'rgba(32, 178, 170, 0.4)',
        'tertiary-fixed': '#ffdbcd',
        outline: '#869391',
        'on-secondary-container': '#ddfffe',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-desktop': '80px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-active': '0 0 15px rgba(32, 178, 170, 0.4)',
        'glow-soft': '0 -5px 20px -5px rgba(32, 178, 170, 0.2)',
        'glow-strong': '0 0 25px rgba(32, 178, 170, 0.55)',
      },
      keyframes: {
        blink: {
          '50%': { opacity: '0' },
        },
        'pulse-line': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        flicker: {
          '0%, 19%, 21%, 23%, 25%, 54%, 56%, 100%': { opacity: '1' },
          '20%, 24%, 55%': { opacity: '0.4' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        glitch: {
          '0%, 100%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 1px)' },
          '40%': { transform: 'translate(-1px, -1px)' },
          '60%': { transform: 'translate(1px, 1px)' },
          '80%': { transform: 'translate(1px, -1px)' },
        },
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        'pulse-line': 'pulse-line 2.5s ease-in-out infinite',
        flicker: 'flicker 3s linear infinite',
        scanline: 'scanline 8s linear infinite',
        'fade-up': 'fade-up 0.6s ease-out forwards',
        glitch: 'glitch 0.3s ease-in-out',
      },
    },
  },
  plugins: [],
} satisfies Config;
