import type { Config } from 'tailwindcss';

/**
 * "Cyber Level Narrative" design system.
 * Tokens ported 1:1 from design_idea/DESIGN.md so the production build
 * matches the approved mock. Animations are added for the game/terminal feel.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#1a1a1a',
        'secondary-container': '#4d4d4d',
        'on-error': '#690005',
        'tertiary-container': '#e9865b',
        'on-surface-variant': '#a8a8a8',
        'on-error-container': '#ffdad6',
        'primary-container': '#5c5c5c',
        'primary-fixed-dim': '#8c8c8c',
        'on-primary': '#1a1a1a',
        'outline-variant': '#3a3a3a',
        'surface-container-low': '#0a0a0a',
        'terminal-bg': '#000000',
        'surface-bright': '#1f1f1f',
        'on-primary-fixed-variant': '#333333',
        'surface-container-high': '#131313',
        'on-secondary-fixed-variant': '#404040',
        'surface-container-lowest': '#030303',
        error: '#ffb4ab',
        tertiary: '#ffb597',
        'surface-container': '#0d0d0d',
        'glass-fill': 'rgba(10, 10, 10, 0.6)',
        'secondary-fixed': '#c2c2c2',
        'on-surface': '#e8e8e8',
        'primary-fixed': '#cfcfcf',
        'tertiary-fixed-dim': '#ffb597',
        'on-background': '#e8e8e8',
        'on-secondary-fixed': '#1a1a1a',
        'error-red': '#FF4B4B',
        'error-container': '#93000a',
        primary: '#ababab',
        'secondary-fixed-dim': '#a0a0a0',
        'on-primary-container': '#d9d9d9',
        'on-secondary': '#262626',
        'inverse-on-surface': '#1f1f1f',
        'on-tertiary': '#591d00',
        'on-tertiary-fixed-variant': '#79300b',
        secondary: '#a0a0a0',
        'inverse-primary': '#6b6b6b',
        'surface-variant': '#1a1a1a',
        background: '#050505',
        'surface-container-highest': '#1a1a1a',
        surface: '#050505',
        'on-tertiary-container': '#632200',
        'on-tertiary-fixed': '#360f00',
        'inverse-surface': '#e8e8e8',
        'surface-dim': '#050505',
        'surface-tint': '#ababab',
        'glow-teal': 'rgba(171, 171, 171, 0.35)',
        'tertiary-fixed': '#ffdbcd',
        outline: '#7a7a7a',
        'on-secondary-container': '#f0f0f0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-desktop': '80px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.15em', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-active': '0 0 15px rgba(171, 171, 171, 0.35)',
        'glow-soft': '0 -5px 20px -5px rgba(171, 171, 171, 0.18)',
        'glow-strong': '0 0 25px rgba(171, 171, 171, 0.5)',
      },
      keyframes: {
        blink: {
          '50%': { opacity: '0' },
        },
        'pulse-line': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        flicker: {
          '0%, 19%, 21%, 23%, 25%, 54%, 56%, 100%': { opacity: '1' },
          '20%, 24%, 55%': { opacity: '0.4' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        glitch: {
          '0%, 100%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 1px)' },
          '40%': { transform: 'translate(-1px, -1px)' },
          '60%': { transform: 'translate(1px, 1px)' },
          '80%': { transform: 'translate(1px, -1px)' },
        },
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        'pulse-line': 'pulse-line 2.5s ease-in-out infinite',
        flicker: 'flicker 3s linear infinite',
        scanline: 'scanline 8s linear infinite',
        'fade-up': 'fade-up 0.6s ease-out forwards',
        glitch: 'glitch 0.3s ease-in-out',
      },
    },
  },
  plugins: [],
} satisfies Config;
